const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generateAgreementPDF = (agreement, landlord, tenant, property, res) => {
  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(res);

  // --- HEADER ---
  doc.fontSize(20).text('RESIDENTIAL RENTAL AGREEMENT', { align: 'center' });
  doc.moveDown();

  // --- PARTIES ---
  doc.fontSize(12).text(`This Agreement is made on ${new Date().toLocaleDateString()}`);
  doc.moveDown();
  doc.text(`BETWEEN: ${landlord.name} ("Landlord")`);
  doc.text(`AND: ${tenant.name} ("Tenant")`);
  doc.moveDown();

  // --- PROPERTY ---
  doc.text('FOR THE PROPERTY AT:');
  doc.text(`${property.address.street}, ${property.address.city}, ${property.address.state}`);
  doc.moveDown();

  // --- TERMS ---
  doc.fontSize(14).text('TERMS AND CONDITIONS', { underline: true });
  doc.fontSize(12);
  doc.moveDown();
  doc.text(`1. TERM: Commencing ${new Date(agreement.term.startDate).toDateString()} and ending ${new Date(agreement.term.endDate).toDateString()}.`);
  doc.moveDown();
  doc.text(`2. RENT: The Tenant agrees to pay Rs. ${agreement.financials.rentAmount.toLocaleString()} per month.`);
  doc.moveDown();
  doc.text(`3. SECURITY DEPOSIT: A refundable deposit of Rs. ${agreement.financials.depositAmount.toLocaleString()} shall be held by the Landlord.`);
  doc.moveDown();
  doc.text(`4. LATE FEE: A late fee of Rs. ${agreement.financials.lateFeeAmount || 0} applies after ${agreement.financials.lateFeeGracePeriodDays || 5} days grace period.`);
  doc.moveDown(2);

  // --- DIGITAL SIGNATURE BLOCK ---
  doc.fontSize(14).text('DIGITAL SIGNATURES', { underline: true });
  doc.moveDown();

  // Landlord signature
  if (agreement.signatures?.landlord?.signed) {
    doc.fontSize(11).text('LANDLORD SIGNATURE:', { continued: false });
    doc.fontSize(10)
      .text(`Name: ${landlord.name}`)
      .text(`Signed At: ${new Date(agreement.signatures.landlord.signedAt).toLocaleString()}`)
      .text(`IP Address: ${agreement.signatures.landlord.ipAddress}`)
      .text(`Status: ✓ Digitally Signed`);
  } else {
    doc.fontSize(11).text('LANDLORD SIGNATURE:');
    doc.fontSize(10).text('Status: ⚠ Pending Signature');
    doc.moveDown();
    doc.text('__________________________');
    doc.text(`${landlord.name} (Landlord)`);
  }

  doc.moveDown(2);

  // Tenant signature
  if (agreement.signatures?.tenant?.signed) {
    doc.fontSize(11).text('TENANT SIGNATURE:', { continued: false });
    doc.fontSize(10)
      .text(`Name: ${tenant.name}`)
      .text(`Signed At: ${new Date(agreement.signatures.tenant.signedAt).toLocaleString()}`)
      .text(`IP Address: ${agreement.signatures.tenant.ipAddress}`)
      .text(`Status: ✓ Digitally Signed`);
  } else {
    doc.fontSize(11).text('TENANT SIGNATURE:');
    doc.fontSize(10).text('Status: ⚠ Pending Signature');
    doc.moveDown();
    doc.text('__________________________');
    doc.text(`${tenant.name} (Tenant)`);
  }

  doc.moveDown(2);

  // Legal disclaimer
  doc.fontSize(9)
    .fillColor('#666666')
    .text('This document was generated by RentifyPro. Digital signatures recorded above constitute legally binding acceptance of the terms herein.', { align: 'center' });

  doc.end();
};
module.exports = { generateAgreementPDF };